theme: jekyll-theme-minimal
title: Svyatoslav I. Maslennikov
logo: me.jpg
description: 'An <a href="https://www.linkedin.com/in/slava-maslennikov-a48b2a20/">Manager, Infrastructure Modernization at SADA</a>'

defaults:
  - scope:
      path: "/"
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post

permalink: /posts/:title/
