theme: jekyll-theme-minimal
title: Svyatoslav I. Maslennikov
logo: me.jpg
description: Owner, Cool Consulting, LLC

defaults:
  - scope:
      path: "/"
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post

permalink: /posts/:title/
