theme: jekyll-theme-minimal
layout: default
title: Slava Maslennikov
logo: logo.png
description: 'A <a href="https://www.linkedin.com/in/slava-maslennikov-a48b2a20/">Senior Cloud Engineer at SADA Systems, Inc.</a>'
