---
- name: install plex pubkey
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: install plex repo
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present

- name: install nginx, certbot and plex
  apt:
    name:
      - nginx
      - python-certbot-nginx
      - certbot
      - plexmediaserver

- name: install nginx config
  copy:
    src: "{{ role_path}}/files/nginx.conf"
    dest: /etc/nginx/
    owner: root
    group: root

- name: enable and start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - plexmediaserver
    - nginx

- name: open firewall ports
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - http
    - https
    - plex
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: run certbot
  command: certbot -n -m me@smaslennikov.com --nginx --domains cereza.pinchesarbol.es --agree-tos
