- name: Install packages on debian
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - mpc
    - ncmpcpp
    - ansible
    - bash-completion
    - dnsutils
    - bitlbee
    - cowsay
    - fail2ban
    - fortune-mod
    - gcc
    - g++
    - git
    - htop
    - lsof
    - mosh
    - mutt
    - newsboat
    - nmap
    - python-dev
    - python-pip
    - rancid
    - reptyr
    - rtorrent
    - screen
    - sqlite
    - sudo
    - tcpdump
    - traceroute
    - vim
    - weechat
    - npm
    - acpi
    - alsa-utils
    - ansible
    - keepassxc
    - libxft-dev
    - libxinerama-dev
    - lm-sensors
    - network-manager
    - network-manager-gnome
    - pavucontrol
    - rxvt-unicode
    - slock
    - urxvt
    - x11-xserver-utils
    - xbacklight
    - xbattbar
    - xinit
    - xinput
    - xss-lock
    - battery-stats
# also dropbox and google chrome from upstream
