---
- name: Configure a personal pear with some of the usual things
  hosts: pear
  become: true
  serial: 100%

  roles:
    - accounts
    - dotfiles
    - packages
    - configs
    - pear-executables
    - clone_my_repos
    - gpg-keys
    - mutt
    - weechat_personal
    - weechat_work
    - firewall
    - plex

  tasks:
    - name: apply sysctl file limits
      sysctl:
        name: fs.file-max
        value: 500000
    - name: apply sysctl tcp port limits
      sysctl:
        name: net.ipv4.ip_local_port_range
        value: 1024 65535
    - name: open some firewall ports
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - 60001-60100/udp
        - 1025-1028
