---
- name: Configure an RPI with some of the usual things
  hosts: rpi
  become: true
  serial: 100%

  roles:
    - accounts

  tasks:
    - name: Add user to GPIO groups
      user:
        name: slava
        groups: gpio,i2c
        append: yes

  roles:
    - dotfiles
    - packages
    - configs
    - fail2ban
    - litter-controller
