---
- name: Configure an RPI with some of the usual things
  hosts: rpi
  become: true
  serial: 100%

  roles:
    - accounts
    - dotfiles
    - packages
    - configs
    - fail2ban
    - litter-controller
