---
- name: Configure a personal VPS with all the usual things
  hosts: slab
  become: true
  serial: 100%

  roles:
    - accounts
    - dotfiles
    - packages
    - configs
    - fail2ban
    - clone_my_repos
    - gpg-keys
    - mutt
    - weechat_personal
    - weechat_work
