---
- name: set timezone
  timezone:
    name: US/Pacific

- name: build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "127.*{{ inventory_hostname }}.*$"
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
