---
- name: set timezone
  timezone:
    name: US/Pacific

- name: build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "127.*{{ inventory_hostname }}.*$"
    line: "127.0.1.1 {{ inventory_hostname }}"
    state: present

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: install fail2ban jail
  copy:
    src: "{{ item }}"
    dest: '/etc/fail2ban/jail.d/'
  with_fileglob:
    - "{{ role_path }}/files/jail.local"

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: install RPI boot config
  copy:
    src: "{{ item }}"
    dest: '/boot/'
  with_fileglob:
    - "{{ role_path }}/files/config.txt"
  when: gpio_hosts is search("{{ inventory_hostname }}")

- name: install RPI wpa_supplicant config
  copy:
    src: "{{ item }}"
    dest: '/etc/wpa_supplicant/'
  with_fileglob:
    - "{{ role_path }}/files/wpa_supplicant.conf"
  when: gpio_hosts is search("{{ inventory_hostname }}")
